---
type: l3leaf

l3leaf:
  defaults:
    platform: EOS
    virtual_router_mac_address: 00:1c:73:00:dc:01
    # VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
    # Assign range larger than total leaf switches
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    # Offset must be >= number of spines
    loopback_ipv4_offset: 2
    # Point to Point Network Summary range, assigned as /31 for each
    # uplink interfaces
    # Assign range larger than total [spines * total potential leafs * 2]
    uplink_ipv4_pool: 172.31.255.0/24
    uplink_switches: [media-spine-1, media-spine-2]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    # mlag pair IP assignment - assign blocks - Assign range larger than
    # total spines + total leafs switches
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
  nodes:
      media-ptp-1:
        id: 1
        mgmt_ip: 10.255.0.13/24
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet1, Ethernet2]
      media-ptp-2:
        id: 2
        mgmt_ip: 10.255.0.14/24
        # Interface configured on SPINES to connect to this leaf
        uplink_switch_interfaces: [Ethernet1, Ethernet2]
